import { Platform, StatusBar } from "react-native";
import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const baseStyles = {
  container: {
    flex: 1,
    backgroundColor: "#F3F5FB",
  },
  pageHeader: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
    backgroundColor: "#0f1c3a",
  },
  heroBackground: {
    width: "100%",
  },
  heroImage: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    transform: [{ scale: 1.02 }],
  },
  heroOverlay: {
    paddingTop: SPACING.xl,
    paddingBottom: SPACING.xl,
    paddingHorizontal: SPACING.lg,
    gap: SPACING.md,
  },
  heroBadge: {
    alignSelf: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  heroBadgeText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.md,
  },
  locationLabel: {
    color: "rgba(255,255,255,0.7)",
    fontSize: FONT_SIZES.sm,
  },
  locationValue: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "700",
    color: COLORS.white,
  },
  loginButton: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  loginButtonText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  profileButton: {
    backgroundColor: "rgba(255,255,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileAvatarSmall: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileButtonLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
  },
  profileButtonName: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 14,
  },
  heroTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: COLORS.white,
    textAlign: "center",
    lineHeight: 40,
    letterSpacing: -1,
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.72)",
    fontSize: FONT_SIZES.sm,
    marginBottom: SPACING.sm,
    lineHeight: 21,
    textAlign: "center",
  },
  heroStats: {
    flexDirection: "row",
    gap: SPACING.md,
    justifyContent: "space-between",
    marginTop: SPACING.sm,
    paddingVertical: SPACING.sm,
    flexWrap: "wrap",
  },
  stat: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.14)",
    paddingVertical: SPACING.sm,
    borderRadius: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  statLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: FONT_SIZES.sm,
  },
  statNumber: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
  footer: {
    marginTop: SPACING.lg,
    backgroundColor: "#0f172a",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.lg,
    paddingBottom: SPACING.xl,
    gap: SPACING.md,
  },
  footerHeader: {
    flexDirection: "row",
    gap: SPACING.sm,
    alignItems: "center",
  },
  footerLogoBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(91, 60, 240, 0.85)",
    alignItems: "center",
    justifyContent: "center",
  },
  footerTitle: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
  footerSubtitle: {
    color: "rgba(255,255,255,0.45)",
    marginTop: 1,
    fontSize: FONT_SIZES.xs,
  },
  footerSocialRow: {
    flexDirection: "row",
    gap: SPACING.xs,
  },
  footerSocialButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  footerColumns: {
    flexDirection: "row",
    gap: SPACING.lg,
  },
  footerHeading: {
    color: COLORS.white,
    fontWeight: "700",
    marginBottom: SPACING.sm,
  },
  footerLink: {
    color: "#d7def1",
    marginBottom: SPACING.xs,
  },
  footerContactRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  footerContactLabel: {
    color: COLORS.white,
    fontWeight: "700",
  },
  footerContactValue: {
    color: "#a5b1d6",
  },
  footerDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  footerBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerBottomText: {
    color: "rgba(255,255,255,0.35)",
    fontSize: FONT_SIZES.xs,
  },
  footerLegalRow: {
    flexDirection: "row",
    gap: SPACING.xs,
    alignItems: "center",
  },
  footerLegalText: {
    color: "rgba(255,255,255,0.35)",
    fontSize: FONT_SIZES.xs,
  },
};
