import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const baseStyles = {
  container: {
    flex: 1,
    backgroundColor: "#F4FBFF",
  },
  pageHeader: {
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  heroBackground: {
    width: "100%",
  },
  heroImage: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    transform: [{ scale: 1.02 }],
  },
  heroOverlay: {
    paddingTop: SPACING.xl + 4,
    paddingBottom: SPACING.xl,
    paddingHorizontal: SPACING.lg,
    gap: SPACING.md,
    //backgroundColor: "rgba(244, 252, 255, 0.78)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(14, 116, 144, 0.12)",
  },
  heroBadge: {
    alignSelf: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    backgroundColor: "rgba(14, 116, 144, 0.14)",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(251, 146, 60, 0.28)",
  },
  heroBadgeText: {
    color: "#0C4A6E",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
    letterSpacing: 0.2,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  locationLabel: {
    color: "rgba(15, 23, 42, 0.5)",
    fontSize: FONT_SIZES.sm,
  },
  locationValue: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "700",
    color: "#075985",
  },
  loginButton: {
    backgroundColor: "rgba(14, 116, 144, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.3)",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 999,
  },
  loginButtonText: {
    color: "#0E7490",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  profileButton: {
    backgroundColor: "rgba(255, 255, 255, 0.75)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.18)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileAvatarSmall: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#0E7490",
    alignItems: "center",
    justifyContent: "center",
  },
  profileButtonLabel: {
    color: "rgba(15, 23, 42, 0.5)",
    fontSize: 11,
  },
  profileButtonName: {
    color: COLORS.text,
    fontWeight: "700",
    fontSize: 14,
  },
  heroTitle: {
    fontSize: 34,
    fontWeight: "800",
    color: "#052E40",
    textAlign: "center",
    lineHeight: 42,
    letterSpacing: -0.8,
  },
  heroSubtitle: {
    color: "#334155",
    fontSize: FONT_SIZES.sm + 1,
    marginBottom: SPACING.xs,
    lineHeight: 22,
    textAlign: "center",
  },
  heroHighlightsRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: SPACING.sm,
    flexWrap: "wrap",
    marginBottom: SPACING.xs,
  },
  heroHighlightChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: SPACING.sm + 2,
    paddingVertical: 6,
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.22)",
    shadowColor: "#0E7490",
    shadowOpacity: 0.09,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  heroHighlightText: {
    color: "#0C4A6E",
    fontWeight: "700",
    fontSize: FONT_SIZES.xs,
  },
  heroMoodRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: SPACING.xs,
    flexWrap: "wrap",
    marginBottom: SPACING.sm,
  },
  heroMoodChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: SPACING.sm + 1,
    paddingVertical: 5,
    backgroundColor: "rgba(255, 244, 230, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(251, 146, 60, 0.34)",
  },
  heroMoodText: {
    color: "#9A3412",
    fontWeight: "700",
    fontSize: 11,
  },
  heroStats: {
    flexDirection: "row",
    gap: SPACING.md,
    justifyContent: "space-between",
    marginTop: SPACING.sm,
    paddingVertical: SPACING.sm,
    flexWrap: "wrap",
  },
  stat: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.72)",
    paddingVertical: SPACING.sm,
    borderRadius: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.2)",
    shadowColor: "#0E7490",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  statLabel: {
    color: "rgba(15, 23, 42, 0.58)",
    fontSize: FONT_SIZES.sm,
  },
  statNumber: {
    color: "#0F172A",
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
  footer: {
    marginTop: SPACING.xl,
    backgroundColor: "transparent",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    paddingBottom: SPACING.xl,
    gap: SPACING.md,
  },
  footerHeader: {
    flexDirection: "row",
    gap: SPACING.sm,
    alignItems: "center",
  },
  footerLogoBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#0E7490",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(251, 146, 60, 0.45)",
  },
  footerTitle: {
    color: COLORS.text,
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
  footerSubtitle: {
    color: COLORS.textLight,
    marginTop: 1,
    fontSize: FONT_SIZES.xs,
  },
  footerSocialRow: {
    flexDirection: "row",
    gap: SPACING.xs,
  },
  footerSocialButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255, 255, 255, 0.86)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.22)",
  },
  footerColumns: {
    flexDirection: "row",
    gap: SPACING.lg,
  },
  footerHeading: {
    color: COLORS.text,
    fontWeight: "700",
    marginBottom: SPACING.sm,
  },
  footerLink: {
    color: COLORS.textLight,
    marginBottom: SPACING.xs,
  },
  footerContactRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  footerContactLabel: {
    color: COLORS.text,
    fontWeight: "700",
  },
  footerContactValue: {
    color: COLORS.textLight,
  },
  footerDivider: {
    height: 1,
    backgroundColor: "rgba(14, 116, 144, 0.14)",
  },
  footerBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerBottomText: {
    color: COLORS.textLight,
    fontSize: FONT_SIZES.xs,
  },
  footerLegalRow: {
    flexDirection: "row",
    gap: SPACING.xs,
    alignItems: "center",
  },
  footerLegalText: {
    color: COLORS.textLight,
    fontSize: FONT_SIZES.xs,
  },
};
