import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const cardStyles = {
  card: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.98)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.12)",
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOpacity: 0.1,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 11 },
    elevation: 8,
    marginBottom: SPACING.md,
  },
  cardCompact: {
    width: 300,
    marginBottom: 0,
  },
  cardWide: {
    width: 340,
    marginBottom: 0,
  },
  cardImageWrapper: {
    position: "relative",
  },
  cardTopTint: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 110,
  },
  cardImage: {
    width: "100%",
    height: 240,
    backgroundColor: COLORS.border,
  },
  cardTopRow: {
    position: "absolute",
    top: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardBadge: {
    backgroundColor: "rgba(2, 132, 199, 0.92)",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.42)",
  },
  cardBadgeText: {
    color: COLORS.white,
    fontSize: FONT_SIZES.xs,
    fontWeight: "700",
  },
  cardBookmark: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
  },
  bookmarkIcon: {
    color: "#E94057",
    fontSize: FONT_SIZES.lg,
  },
  cardRating: {
    position: "absolute",
    bottom: SPACING.sm,
    left: SPACING.sm,
    backgroundColor: "rgba(15, 23, 42, 0.62)",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: 999,
  },
  cardRatingText: {
    color: COLORS.white,
    fontWeight: "700",
  },
  cardBody: {
    padding: SPACING.lg,
    paddingTop: SPACING.md + 4,
    paddingBottom: SPACING.lg + 4,
    gap: SPACING.sm,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.xs,
    marginBottom: SPACING.xs,
  },
  cardTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "800",
    color: COLORS.text,
    flex: 1,
  },
  cardSubtitle: {
    color: "#475569",
    fontSize: FONT_SIZES.md,
    lineHeight: 22,
  },
  cardDistanceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  cardDistance: {
    color: "#0E7490",
    fontWeight: "700",
  },
  popularCard: {
    width: 300,
    borderRadius: 30,
    overflow: "hidden",
    height: 336,
    backgroundColor: "rgba(255,255,255,0.96)",
    shadowColor: "#0F172A",
    shadowOpacity: 0.18,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.18)",
  },
  popularImage: {
    width: "100%",
    height: "100%",
    justifyContent: "flex-end",
  },
  popularFade: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "100%",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  popularTopRow: {
    position: "absolute",
    top: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  compactBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(14, 116, 144, 0.92)",
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  compactBadgeText: {
    color: "#fff",
    fontSize: FONT_SIZES.xs,
    fontWeight: "700",
  },
  popularTextBlock: {
    position: "absolute",
    left: SPACING.md,
    right: SPACING.md,
    bottom: SPACING.md,
  },
  popularTitle: {
    color: COLORS.white,
    fontSize: FONT_SIZES.lg,
    lineHeight: 24,
    fontWeight: "900",
  },
  popularMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  popularMeta: {
    color: COLORS.white,
    fontSize: FONT_SIZES.sm,
    flex: 1,
    fontWeight: "700",
  },
  popularImageRadius: {
    borderRadius: 30,
  },
  popularGlowOrb: {
    position: "absolute",
    right: -42,
    top: -34,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  popularShine: {
    position: "absolute",
    top: -44,
    bottom: -44,
    width: 58,
    backgroundColor: "rgba(255,255,255,0.58)",
  },
  popularRatingPill: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.60)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
  },
  popularDistancePill: {
    position: "absolute",
    top: 54,
    right: SPACING.md,
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: "rgba(236, 254, 255, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
  },
  popularDistanceText: {
    color: "#0E7490",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
  },
  popularGlassPanel: {
    padding: SPACING.md,
    borderRadius: 22,
    backgroundColor: "rgba(15, 23, 42, 0.42)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
  },
  popularSubtitle: {
    marginTop: 6,
    color: "rgba(255,255,255,0.82)",
    fontSize: FONT_SIZES.xs,
    lineHeight: 17,
    fontWeight: "500",
  },
  popularActionRow: {
    marginTop: SPACING.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  popularHintPill: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(14, 116, 144, 0.82)",
  },
  popularHintText: {
    color: "#FFFFFF",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
  },
  popularArButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(236, 254, 255, 0.94)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  cardMeta: {
    color: COLORS.textLight,
    flex: 1,
    fontSize: FONT_SIZES.sm,
  },
  cardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  loadMoreCard: {
    width: 200,
    height: 320,
    backgroundColor: "#F0FDFA",
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "rgba(14, 116, 144, 0.28)",
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: SPACING.md,
    gap: SPACING.sm,
  },
  loadMoreIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#ECFEFF",
    justifyContent: "center",
    alignItems: "center",
  },
  loadMoreText: {
    color: "#475569",
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
};
