import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const cardStyles = {
  card: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.98)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.12)",
    overflow: "hidden",
    shadowColor: "#0F172A",
    shadowOpacity: 0.1,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 11 },
    elevation: 8,
    marginBottom: SPACING.md,
  },
  cardCompact: {
    width: 300,
    marginBottom: 0,
  },
  cardWide: {
    width: 340,
    marginBottom: 0,
  },
  cardImageWrapper: {
    position: "relative",
  },
  cardTopTint: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 110,
  },
  cardImage: {
    width: "100%",
    height: 240,
    backgroundColor: COLORS.border,
  },
  cardTopRow: {
    position: "absolute",
    top: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardBadge: {
    backgroundColor: "rgba(2, 132, 199, 0.92)",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.42)",
  },
  cardBadgeText: {
    color: COLORS.white,
    fontSize: FONT_SIZES.xs,
    fontWeight: "700",
  },
  cardBookmark: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
  },
  bookmarkIcon: {
    color: "#E94057",
    fontSize: FONT_SIZES.lg,
  },
  cardRating: {
    position: "absolute",
    bottom: SPACING.sm,
    left: SPACING.sm,
    backgroundColor: "rgba(15, 23, 42, 0.62)",
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: 999,
  },
  cardRatingText: {
    color: COLORS.white,
    fontWeight: "700",
  },
  cardBody: {
    padding: SPACING.lg,
    paddingTop: SPACING.md + 4,
    paddingBottom: SPACING.lg + 4,
    gap: SPACING.sm,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.xs,
    marginBottom: SPACING.xs,
  },
  cardTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "800",
    color: COLORS.text,
    flex: 1,
  },
  cardSubtitle: {
    color: "#475569",
    fontSize: FONT_SIZES.md,
    lineHeight: 22,
  },
  cardDistanceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  cardDistance: {
    color: "#0E7490",
    fontWeight: "700",
  },
  popularCard: {
    width: 300,
    borderRadius: 32,
    overflow: "hidden",
    height: 320,
    backgroundColor: "#ffffff",
    shadowColor: "#0F172A",
    shadowOpacity: 0.14,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
  },
  popularImage: {
    width: "100%",
    height: "100%",
    justifyContent: "flex-end",
  },
  popularFade: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "100%",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  popularTopRow: {
    position: "absolute",
    top: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  compactBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(2, 132, 199, 0.9)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
  },
  compactBadgeText: {
    color: "#fff",
    fontSize: FONT_SIZES.xs,
    fontWeight: "700",
  },
  popularTextBlock: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.xl,
    paddingTop: SPACING.xl * 2,
    gap: 2,
  },
  popularTitle: {
    color: COLORS.white,
    fontSize: FONT_SIZES.md + 2,
    fontWeight: "800",
  },
  popularMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  popularMeta: {
    color: COLORS.white,
    fontSize: FONT_SIZES.sm,
    flex: 1,
  },
  popularRating: {
    bottom: "auto",
    top: SPACING.md,
    left: "auto",
    right: SPACING.md,
    position: "absolute",
  },
  popularImageRadius: {
    borderRadius: 28,
  },
  cardMeta: {
    color: COLORS.textLight,
    flex: 1,
    fontSize: FONT_SIZES.sm,
  },
  cardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  loadMoreCard: {
    width: 200,
    height: 320,
    backgroundColor: "#F0FDFA",
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "rgba(14, 116, 144, 0.28)",
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: SPACING.md,
    gap: SPACING.sm,
  },
  loadMoreIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#ECFEFF",
    justifyContent: "center",
    alignItems: "center",
  },
  loadMoreText: {
    color: "#475569",
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
};
