import { Platform } from "react-native";
import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const detailStyles = {
  detailOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  detailSheet: {
    flex: 1,
    backgroundColor: "#000",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: "hidden",
  },
  detailContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  detailTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: SPACING.sm,
  },
  detailTitle: {
    fontSize: FONT_SIZES.xl + 2,
    fontWeight: "800",
    color: COLORS.text,
  },
  detailSubtitle: {
    color: COLORS.textLight,
    lineHeight: 20,
    marginTop: SPACING.xs,
    marginBottom: SPACING.md,
  },
  detailMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginTop: SPACING.sm,
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F3F4F6",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: 14,
  },
  metaPillText: {
    fontWeight: "700",
    color: COLORS.text,
    fontSize: FONT_SIZES.sm,
  },
  infoRow: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
    marginTop: SPACING.sm,
  },
  infoPill: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: SPACING.md,
  },
  infoLabel: {
    color: COLORS.textLight,
    marginBottom: SPACING.xs,
  },
  infoValue: {
    color: COLORS.text,
    fontWeight: "600",
  },
  actionButtonRow: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: SPACING.md,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: SPACING.xs,
  },
  actionButtonPrimary: {
    backgroundColor: "#5B3CF0",
    elevation: 5,
  },
  actionButtonPrimaryText: {
    color: COLORS.white,
    fontWeight: "700",
  },
  actionButtonSecondary: {
    backgroundColor: "#F6F7FB",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  actionButtonSecondaryText: {
    color: COLORS.text,
    fontWeight: "700",
  },
  sliderContainer: {
    position: "relative",
    marginVertical: 0,
  },
  infoSlide: {
    backgroundColor: "transparent",
    borderRadius: 20,
    flex: 1,
    overflow: "hidden",
  },
  transitionSlide: {
    backgroundColor: "#F8FAFC",
    borderRadius: 20,
    padding: SPACING.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  infoSlideGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
  },
  infoSlideScroll: {
    gap: SPACING.md,
    paddingBottom: SPACING.xl,
  },
  infoSlideHeader: {
    gap: SPACING.xs,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.sm,
  },
  infoSlideTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
    marginBottom: SPACING.xs,
  },
  infoSlideTagPrimary: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(91, 60, 240, 0.12)",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: 14,
  },
  infoSlideTagText: {
    fontWeight: "700",
    color: COLORS.text,
  },
  infoSlideTitle: {
    fontSize: FONT_SIZES.xl + 2,
    fontWeight: "800",
    color: COLORS.text,
  },
  infoSlideDescription: {
    color: COLORS.text,
    lineHeight: 20,
  },
  infoSlideGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  infoSlideCard: {
    width: "48%",
    backgroundColor: "#F7F8FD",
    borderRadius: 14,
    padding: SPACING.md,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.04)",
  },
  infoSlideCardLabel: {
    color: COLORS.textLight,
    fontSize: FONT_SIZES.sm,
  },
  infoSlideCardValue: {
    color: COLORS.text,
    fontWeight: "700",
  },
  infoSlideActions: {
    flexDirection: "row",
    gap: SPACING.sm,
    flexWrap: "wrap",
    paddingHorizontal: SPACING.lg,
  },
  arPreviewCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: SPACING.md,
    elevation: 3,
  },
  arPreviewTitle: {
    fontWeight: "800",
    color: COLORS.text,
  },
  modelChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
  },
  modelChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    backgroundColor: "#F8F8FD",
  },
  modelChipActive: {
    backgroundColor: "#5B3CF0",
    borderColor: "#5B3CF0",
  },
  modelChipText: {
    color: COLORS.text,
    fontSize: FONT_SIZES.sm,
  },
  modelChipTextActive: {
    color: COLORS.white,
    fontWeight: "700",
  },
  detailImage: {
    width: "100%",
    height: "100%",
  },
  imageInfoOverlay: {
    position: "absolute",
    inset: 0,
    justifyContent: "flex-end",
    padding: SPACING.lg,
    paddingBottom: SPACING.xl,
    gap: SPACING.sm,
  },
  imageBadge: {
    backgroundColor: "rgba(91, 60, 240, 0.95)",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 20,
  },
  imageBadgeText: {
    color: COLORS.white,
    fontSize: FONT_SIZES.md,
    fontWeight: "700",
  },
  moreInfoButton: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderRadius: 25,
    alignItems: "center",
  },
  moreInfoText: {
    color: "#5B3CF0",
    fontSize: FONT_SIZES.md,
    fontWeight: "700",
  },
  detailInfoPanel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    elevation: 10,
  },
  detailInfoContent: {
    padding: SPACING.xl,
    gap: SPACING.md,
  },
  detailInfoTitle: {
    fontSize: FONT_SIZES.xxl,
    fontWeight: "800",
    color: COLORS.text,
  },
  detailInfoDescription: {
    fontSize: FONT_SIZES.md,
    color: COLORS.textLight,
    lineHeight: 24,
  },
  detailInfoStats: {
    flexDirection: "row",
    gap: SPACING.md,
  },
  detailInfoStat: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    backgroundColor: "#F7F8FD",
    padding: SPACING.md,
    borderRadius: 16,
  },
  detailInfoStatText: {
    fontSize: FONT_SIZES.sm,
    fontWeight: "600",
    color: COLORS.text,
  },
  detailInfoBackdrop: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  modernTopControls: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 30,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  modernCircularBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  thumbnailGalleryContainer: {
    position: 'absolute',
    bottom: 40,
    insetHorizontal: 0,
    zIndex: 10,
  },
  thumbnailWrap: {
    width: 65,
    height: 65,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  thumbnailWrapActive: {
    borderColor: '#ffffff',
    transform: [{ scale: 1.1 }],
    elevation: 6,
  },
};
