import { Platform } from "react-native";
import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const modalStyles = {
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    padding: SPACING.lg,
  },
  modalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: SPACING.lg,
    maxHeight: "80%",
    width: "100%",
  },
  modalScroll: {
    gap: SPACING.sm,
    paddingBottom: SPACING.md,
  },
  modalHint: {
    color: COLORS.textLight,
    fontSize: FONT_SIZES.sm,
    marginTop: SPACING.xs,
  },
  modalAllButton: {
    marginTop: SPACING.xs,
    borderRadius: 12,
    paddingVertical: SPACING.sm,
    alignItems: "center",
    backgroundColor: "#F3F4FF",
    borderWidth: 1,
    borderColor: "#E0E7FF",
  },
  modalAllButtonText: {
    color: "#4338CA",
    fontWeight: "700",
  },
  modalTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: "bold",
    color: COLORS.text,
  },
  modalSubtitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "600",
    color: COLORS.text,
  },
  modalActions: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  modalSecondary: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingVertical: SPACING.sm,
    alignItems: "center",
  },
  modalSecondaryText: {
    color: COLORS.text,
    fontWeight: "600",
  },
  modalPrimary: {
    flex: 1.5,
    backgroundColor: "#EF4444", // Red for logout
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  modalPrimaryText: {
    color: COLORS.white,
    fontWeight: "800",
    fontSize: 14,
  },
  // Profile Modal
  profileCard: {
    backgroundColor: COLORS.white,
    borderRadius: 32,
    padding: SPACING.lg,
    width: "100%",
    maxHeight: "90%",
    shadowColor: "#0F172A",
    shadowOpacity: 0.15,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  profileHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileHeaderTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  profileTitleText: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "700",
    color: COLORS.text,
  },
  profileCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#eef2ff",
  },
  profileName: {
    fontSize: FONT_SIZES.md,
    fontWeight: "700",
    color: COLORS.text,
  },
  profileEmail: {
    color: COLORS.textLight,
    fontSize: FONT_SIZES.sm,
  },
  profileUnverifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 3,
  },
  profileUnverifiedText: {
    color: "#D97706",
    fontSize: FONT_SIZES.xs,
    fontWeight: "600",
  },
  profileInfoGroup: {
    gap: SPACING.xs,
  },
  profileItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    backgroundColor: "#FFFFFF",
    padding: SPACING.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    marginBottom: 8,
  },
  profileItemLabel: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "700",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  profileItemText: {
    color: COLORS.text,
    flex: 1,
    fontSize: 14,
  },
  profileActions: {
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: SPACING.md,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  profileRouteItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    backgroundColor: "#FFFFFF",
    padding: SPACING.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    shadowColor: "#4F46E5",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    marginBottom: 12,
  },
  profileRouteIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(91, 60, 240, 0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileRouteTitle: {
    color: "#1E293B",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm + 1,
  },
  profileRouteDesc: {
    color: COLORS.textLight,
    fontSize: 11,
    marginTop: 2,
    lineHeight: 14,
  },
  // Unverified Alert in Profile
  unverifiedAlert: {
    backgroundColor: "#FFFBEB",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#FEF3C7",
    padding: SPACING.md,
    marginTop: 4,
    gap: SPACING.md,
  },
  unverifiedAlertContent: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  unverifiedAlertIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FEF3C7",
    alignItems: "center",
    justifyContent: "center",
  },
  unverifiedAlertTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#92400E",
  },
  unverifiedAlertText: {
    fontSize: 12,
    color: "#B45309",
    marginTop: 2,
    lineHeight: 16,
  },
  unverifiedAlertButton: {
    backgroundColor: "#F59E0B",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  unverifiedAlertButtonText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: "700",
  },
  // Email Verification Modal
  verificationCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    width: "100%",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    overflow: "hidden",
  },
  verificationHeader: {
    backgroundColor: "#F8FAFC",
    padding: SPACING.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  verificationIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  verificationTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.text,
  },
  verificationSubtitle: {
    fontSize: 13,
    color: COLORS.textLight,
    marginTop: 1,
  },
  verificationBody: {
    padding: SPACING.lg,
    gap: SPACING.lg,
  },
  verificationText: {
    fontSize: 14,
    color: COLORS.textLight,
    lineHeight: 20,
  },
  verificationActionRow: {
    alignItems: "center",
  },
  verificationRequestBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E0E7FF",
    backgroundColor: "#F5F3FF",
  },
  verificationRequestBtnText: {
    color: "#5B3CF0",
    fontWeight: "600",
    fontSize: 13,
  },
  tokenInputGroup: {
    gap: 8,
  },
  tokenInputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.text,
    marginLeft: 4,
  },
  tokenInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    padding: SPACING.md,
    fontSize: 14,
    color: COLORS.text,
  },
  verificationStatusBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: SPACING.md,
    borderRadius: 12,
  },
  statusBoxError: {
    backgroundColor: "#FEF2F2",
  },
  statusBoxSuccess: {
    backgroundColor: "#F0FDF4",
  },
  verificationStatusText: {
    fontSize: 13,
    fontWeight: "500",
    flex: 1,
  },
  verificationFooter: {
    padding: SPACING.lg,
    flexDirection: "row",
    gap: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  verifyModalConfirmBtn: {
    flex: 2,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#5B3CF0",
  },
  verifyModalConfirmBtnText: {
    color: COLORS.white,
    fontWeight: "700",
  },
  // Agency Modal
  agencyModalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    overflow: "hidden",
    width: "100%",
    elevation: 8,
  },
  agencyModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: "#F5F4FF",
    gap: SPACING.sm,
  },
  agencyIcon: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: "rgba(123,91,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  agencyTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "800",
    color: COLORS.text,
  },
  agencySubtitle: {
    color: COLORS.textLight,
    fontSize: FONT_SIZES.sm,
  },
  agencyBody: {
    padding: SPACING.lg,
    gap: SPACING.sm,
  },
  agencyLogo: {
    width: "100%",
    height: 160,
    borderRadius: 16,
  },
  agencyDescription: {
    color: COLORS.text,
    lineHeight: 20,
  },
  agencyInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    padding: SPACING.sm,
    borderRadius: 12,
    backgroundColor: "#F7F8FD",
  },
  agencyInfoText: {
    color: COLORS.text,
    flex: 1,
  },
  // Payment Modal
  paymentCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    overflow: "hidden",
    width: "100%",
    elevation: 8,
  },
  paymentHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
  },
  paymentIcon: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: "rgba(123,91,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  paymentTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "800",
    color: COLORS.text,
  },
  paymentPackageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    padding: SPACING.md,
    backgroundColor: "#F8F8FF",
  },
  paymentPackageTitle: {
    fontWeight: "800",
    color: COLORS.text,
    fontSize: FONT_SIZES.md,
  },
  paymentPackagePriceValue: {
    fontWeight: "800",
    color: COLORS.text,
    fontSize: FONT_SIZES.lg,
  },
  paymentInput: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    backgroundColor: "#F9FAFB",
  },
  paymentSecureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    borderRadius: 12,
    backgroundColor: "#ECFDF3",
    padding: SPACING.sm,
    borderWidth: 1,
    borderColor: "rgba(5,150,105,0.2)",
  },
  paymentConfirmGradient: {
    borderRadius: 14,
    paddingVertical: SPACING.md,
    alignItems: "center",
  },
  paymentConfirmText: {
    color: COLORS.white,
    fontWeight: "800",
    fontSize: FONT_SIZES.md,
  },
  // Filter Bottom Sheet
  filterBottomSheetOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  filterBottomSheet: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.xl + 20,
    paddingTop: 12,
    maxHeight: "85%",
    elevation: 20,
  },
  bottomSheetIndicator: {
    width: 40,
    height: 4,
    backgroundColor: "#E2E8F0",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  filterModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  distanceControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    marginVertical: 24,
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 20,
  },
  distanceValueText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.5,
  },
  distanceStepButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  quickDistanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  distanceChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  distanceChipActive: {
    backgroundColor: '#EEF2FF',
    borderColor: '#5B3CF0',
  },
  filterApplyButton: {
    backgroundColor: "#0F172A",
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    elevation: 5,
  },
  filterApplyButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  // Map Modal
  mapContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  mapHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SPACING.lg,
    paddingTop: Platform.OS === "ios" ? 100 : SPACING.xl,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  mapTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: "700",
    color: COLORS.text,
  },
  mapCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.border,
    justifyContent: "center",
    alignItems: "center",
  },
  mapCloseText: {
    fontSize: 30,
    fontWeight: "300",
    color: COLORS.text,
  },
  paginationDotsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: SPACING.lg,
    marginBottom: SPACING.md,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.border,
    marginHorizontal: 4,
  },
  paginationDotActive: {
    width: 24,
    backgroundColor: COLORS.primary,
  },
  // AR WebView Modal
  arClose: {
    position: "absolute",
    top: Platform.OS === "ios" ? 54 : 30,
    right: 20,
    zIndex: 10,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  arCloseText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  // Verification / Generic small close button
  closeBtnSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  verifyModalCloseBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  verifyModalCloseBtnText: {
    color: COLORS.text,
    fontWeight: "600",
  },
  // ── Agency Modal extras ──────────────────────────────
  agencyHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  agencyInfoBox: {
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    padding: 14,
    gap: 6,
  },
  agencyInfoTitle: {
    fontWeight: "700",
    color: COLORS.text,
    fontSize: 14,
    marginBottom: 2,
  },
  agencyContactBox: {
    gap: 8,
  },
  agencyContactItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F8FAFC",
    padding: 10,
    borderRadius: 10,
  },
  agencyContactText: {
    color: COLORS.text,
    flex: 1,
  },
  agencyCloseButton: {
    backgroundColor: "#5B3CF0",
    paddingVertical: 14,
    margin: 16,
    borderRadius: 14,
    alignItems: "center",
  },
  agencyCloseButtonText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 15,
  },
  // ── Payment Modal extras ─────────────────────────────
  paymentHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  paymentSubtitle: {
    color: COLORS.textLight,
    fontSize: 12,
    marginTop: 1,
  },
  paymentPackageSubtitle: {
    color: COLORS.textLight,
    fontSize: 13,
    marginTop: 2,
  },
  paymentPackagePriceLabel: {
    color: COLORS.textLight,
    fontSize: 11,
    fontWeight: "600",
    marginBottom: 2,
  },
  paymentBody: {
    padding: 16,
    gap: 12,
    paddingBottom: 24,
  },
  paymentRow: {
    flexDirection: "row",
    gap: 12,
  },
  paymentSecureIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
  },
  paymentSecureText: {
    color: "#065F46",
    fontWeight: "600",
    fontSize: 13,
    flex: 1,
  },
  paymentConfirm: {
    borderRadius: 14,
    overflow: "hidden",
    marginTop: 4,
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    fontWeight: "600",
    color: COLORS.text,
    fontSize: 13,
  },
  // ── Filter Modal extras ──────────────────────────────
  quickRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  quickChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  quickChipActive: {
    backgroundColor: "#EEF2FF",
    borderColor: "#5B3CF0",
  },
  quickChipText: {
    color: "#64748B",
    fontWeight: "600",
    fontSize: 13,
  },
  quickChipTextActive: {
    color: "#5B3CF0",
    fontWeight: "700",
  },
  distanceChipText: {
    color: "#475569",
    fontWeight: "600",
    fontSize: 13,
  },
  distanceChipTextActive: {
    color: "#5B3CF0",
    fontWeight: "700",
  },
  distanceValueBox: {
    alignItems: "center",
    minWidth: 80,
  },
};
