import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const packageStyles = {
  packageList: {
    paddingHorizontal: SPACING.md,
  },
  packageListContent: {
    gap: SPACING.md,
    paddingRight: SPACING.lg,
  },
  packageCard: {
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: 26,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.18)",
    shadowColor: "#156436",
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 9,
  },
  packageImageWrapper: {
    height: 210,
    position: "relative",
    overflow: "hidden",
  },
  packageImage: {
    width: "100%",
    height: "100%",
  },
  packageImageFallback: {
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.xs,
    paddingHorizontal: SPACING.md,
  },
  packageFallbackText: {
    color: COLORS.white,
    fontWeight: "700",
    textAlign: "center",
  },
  packageImageOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
  },
  packageImageGlowOrb: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    right: -34,
    top: -28,
    backgroundColor: "rgba(255, 255, 255, 0.34)",
  },
  packageImageShine: {
    position: "absolute",
    top: -42,
    bottom: -42,
    width: 64,
    backgroundColor: "rgba(255, 255, 255, 0.62)",
  },
  packageBadgeRow: {
    position: "absolute",
    top: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  packageDiscount: {
    backgroundColor: "#DC2626",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  packageDiscountText: {
    color: COLORS.white,
    fontWeight: "800",
    fontSize: FONT_SIZES.sm,
  },
  packageTag: {
    backgroundColor: "rgba(255,255,255,0.95)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  packageTagText: {
    color: "#0F172A",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  packageLocationRow: {
    position: "absolute",
    bottom: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  packageLocationChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(15, 23, 42, 0.68)",
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 999,
  },
  packageLocationText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: FONT_SIZES.xs,
  },
  packageHeroMetricRow: {
    position: "absolute",
    top: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  packageHeroMetric: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(15, 23, 42, 0.34)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
  },
  packageHeroMetricText: {
    color: "#FFFFFF",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
  },
  packageBody: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.lg,
  },
  packageBodyContent: {
    gap: SPACING.sm,
  },
  packageVibeRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 2,
  },
  packageVibeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "rgba(20, 184, 166, 0.22)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  packageVibeText: {
    color: "#0D4525",
    fontWeight: "700",
    fontSize: FONT_SIZES.xs,
  },
  packageTitle: {
    fontSize: 21,
    fontWeight: "900",
    color: "#0F172A",
    lineHeight: 28,
  },
  packageDescription: {
    color: "#64748B",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500",
  },
  packageRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  packageRatingText: {
    color: "#0F172A",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  packageAgency: {
    color: "#156436",
    fontWeight: "600",
    fontSize: FONT_SIZES.sm,
  },
  packageSubtitle: {
    color: "#475569",
    lineHeight: 22,
    fontSize: 15,
  },
  packageMetaCleanRow: {
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: 4,
  },
  packageMetaCleanItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  packageMetaCleanText: {
    color: "#475569",
    fontWeight: "600",
    fontSize: FONT_SIZES.sm,
  },
  packageMetaGrid: {
    flexDirection: "row",
    gap: 10,
    marginTop: 2,
  },
  packageMetricCard: {
    flex: 1,
    minHeight: 62,
    borderRadius: 18,
    padding: 11,
    backgroundColor: "rgba(248, 250, 252, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.12)",
  },
  packageMetricLabel: {
    marginTop: 6,
    color: "#94A3B8",
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  packageMetricValue: {
    marginTop: 2,
    color: "#0F172A",
    fontSize: FONT_SIZES.sm,
    fontWeight: "900",
  },
  packageIncludesClean: {
    marginTop: SPACING.xs,
    gap: 6,
  },
  packageRouteBlock: {
    marginTop: 2,
    gap: 10,
  },
  packageRouteHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  packageRouteTitle: {
    color: "#156436",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  packageRouteScroller: {
    gap: 8,
    paddingRight: SPACING.md,
  },
  packageRouteVerticalList: {
    gap: 8,
  },
  packageRouteChip: {
    width: 156,
    minHeight: 52,
    borderRadius: 15,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  packageRouteChipVertical: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: "rgba(248, 250, 252, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.13)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    position: "relative",
  },
  packageRouteLine: {
    position: "absolute",
    left: 24,
    top: 42,
    bottom: -16,
    width: 1,
    backgroundColor: "rgba(14, 116, 144, 0.16)",
  },
  packageRouteIndex: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#ECFEFF",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  packageRouteIndexText: {
    color: "#156436",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
  },
  packageRouteInfo: {
    flex: 1,
    minWidth: 0,
  },
  packageRouteName: {
    color: "#0F172A",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
  },
  packageRouteMeta: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 2,
  },
  packageRouteChipMuted: {
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 7,
  },
  packageRouteMutedText: {
    color: "#64748B",
    fontSize: FONT_SIZES.xs,
    fontWeight: "700",
  },
  packageRouteMoreChip: {
    alignSelf: "flex-start",
    minWidth: 58,
    minHeight: 34,
    borderRadius: 15,
    backgroundColor: "rgba(249, 115, 22, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(249, 115, 22, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  packageRouteMoreText: {
    color: "#C2410C",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
  },
  packageIncludeCleanRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  packageIncludeBullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#FE6C01",
  },
  packageIncludeCleanText: {
    color: "#334155",
    fontSize: 14,
  },
  packageDivider: {
    height: 1,
    backgroundColor: "#F1F5F9",
    marginVertical: SPACING.md,
  },
  packageFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: SPACING.md,
    marginTop: SPACING.md,
    paddingTop: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: "rgba(226, 232, 240, 0.86)",
  },
  packagePriceCol: {
    flex: 1,
  },
  packagePriceNote: {
    color: "#64748B",
    fontSize: FONT_SIZES.xs,
    textTransform: "uppercase",
    fontWeight: "700",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  packagePrice: {
    color: "#0F172A",
    fontWeight: "800",
    fontSize: 24,
  },
  packageButtonClean: {
    backgroundColor: "#FE6C01",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 128,
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 18,
    gap: 8,
    shadowColor: "#FE6C01",
    shadowOpacity: 0.26,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
  },
  packageButtonCleanText: {
    color: COLORS.white,
    fontWeight: "900",
    fontSize: FONT_SIZES.md,
  },
  packageReserveGlow: {
    shadowColor: "#FE6C01",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
  },
  packageDetailHint: {
    color: "#156436",
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
    marginBottom: 4,
  },
  agencyChip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
    shadowColor: "#156436",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    marginRight: SPACING.sm,
  },
  agencyChipText: {
    color: COLORS.text,
    fontWeight: "600",
    maxWidth: 180,
  },
  horizontalList: {
    paddingHorizontal: SPACING.lg,
    gap: SPACING.md,
    paddingRight: SPACING.xl,
  },
  agencyFilterWrap: {
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.sm,
  },
  agencySearchBox: {
    minHeight: 46,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    marginBottom: 12,
    shadowColor: "#156436",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  agencySearchInput: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 10,
    color: "#0F172A",
    fontSize: FONT_SIZES.md,
    fontWeight: "600",
  },
  agencySearchClear: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
  },
  agencyFilterScroller: {
    paddingRight: SPACING.lg,
    gap: 12,
  },
  agencyFilterColumn: {
    width: 310,
    gap: 10,
  },
  agencyPageDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingTop: 10,
  },
  agencyPageDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(14, 116, 144, 0.2)",
  },
  agencyPageDotActive: {
    width: 18,
    backgroundColor: "#156436",
  },
  agencyFilterCard: {
    minHeight: 62,
    width: "100%",
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.94)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.12)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    shadowColor: "#156436",
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  agencyFilterCardActive: {
    backgroundColor: "#E8FFF7",
    borderColor: "rgba(20, 184, 166, 0.48)",
    shadowOpacity: 0.13,
  },
  agencyFilterIcon: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "rgba(14, 116, 144, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  agencyFilterIconActive: {
    backgroundColor: "#156436",
  },
  agencyFilterInfo: {
    flex: 1,
    minWidth: 0,
  },
  agencyFilterName: {
    color: "#0F172A",
    fontWeight: "800",
    fontSize: FONT_SIZES.md,
  },
  agencyFilterMeta: {
    color: "#64748B",
    fontSize: FONT_SIZES.xs,
    marginTop: 2,
    fontWeight: "600",
  },
  agencyFilterInfoButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(14, 116, 144, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  agencyEmptyText: {
    color: "#64748B",
    fontWeight: "600",
    textAlign: "center",
    paddingVertical: SPACING.md,
  },
  agencyMoreButton: {
    minHeight: 62,
    width: "100%",
    borderRadius: 15,
    backgroundColor: "rgba(20, 184, 166, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(20, 184, 166, 0.28)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  agencyMoreButtonFull: {
    minHeight: 134,
  },
  agencyMoreText: {
    color: "#156436",
    fontWeight: "800",
    fontSize: FONT_SIZES.sm,
  },
  packageColumnList: {
    paddingHorizontal: SPACING.lg,
    gap: SPACING.lg,
    alignItems: "center",
    paddingBottom: SPACING.md,
  },
  packageMoreButton: {
    minHeight: 46,
    alignSelf: "stretch",
    borderRadius: 16,
    backgroundColor: "#156436",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#156436",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  packageMoreText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: FONT_SIZES.sm,
  },
  
  // Filtering & Empty Agency States
  clearFilterBtn: {
    backgroundColor: "rgba(20, 184, 166, 0.14)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(20, 184, 166, 0.28)",
  },
  clearFilterText: {
    color: "#0D4525",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  emptyAgencyState: {
    marginHorizontal: SPACING.lg,
    backgroundColor: "rgba(255,255,255,0.72)",
    borderRadius: 24,
    padding: 28,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.12)",
    marginTop: 10,
    marginBottom: 20,
  },
  emptyAgencyStateCompact: {
    paddingVertical: 24,
    marginBottom: 10,
  },
  emptyAgencyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#ECFEFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.12)",
  },
  emptyAgencyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 8,
    textAlign: "center",
  },
  emptyAgencySub: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  emptyAgencyActions: {
    alignSelf: "stretch",
    gap: 10,
  },
  restoreButton: {
    backgroundColor: "#FE6C01",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    elevation: 4,
    shadowColor: "#FE6C01",
    shadowOpacity: 0.28,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  restoreButtonText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
  restoreButtonSecondary: {
    minHeight: 44,
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.22)",
    alignItems: "center",
    justifyContent: "center",
  },
  restoreButtonSecondaryText: {
    color: "#156436",
    fontWeight: "800",
    fontSize: FONT_SIZES.sm,
  },
  packageDetailCard: {
    backgroundColor: COLORS.white,
    borderRadius: 26,
    overflow: "hidden",
    width: "100%",
    maxHeight: "94%",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
  },
  packageDetailImage: {
    width: "100%",
    height: 220,
  },
  packageDetailBody: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
    gap: SPACING.md,
  },
  packageDetailTitle: {
    color: "#0F172A",
    fontWeight: "800",
    fontSize: FONT_SIZES.xl,
    lineHeight: 30,
  },
  packageDetailDescription: {
    color: "#475569",
    fontSize: FONT_SIZES.sm,
    lineHeight: 21,
  },
  packageDetailRouteSection: {
    gap: SPACING.md,
  },
  packageDetailSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  packageDetailSectionIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#ECFEFF",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  packageDetailSectionTitle: {
    color: "#0F172A",
    fontSize: FONT_SIZES.md,
    fontWeight: "800",
  },
  packageDetailSectionSubtitle: {
    color: "#64748B",
    fontSize: FONT_SIZES.xs,
    fontWeight: "600",
    marginTop: 2,
  },
  packageDetailRouteScroller: {
    gap: SPACING.sm,
    paddingRight: SPACING.md,
  },
  packageDetailRouteCard: {
    width: 178,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
    overflow: "hidden",
    shadowColor: "#156436",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  packageDetailRouteMedia: {
    height: 92,
    position: "relative",
    backgroundColor: "#F1F5F9",
  },
  packageDetailRouteImage: {
    width: "100%",
    height: "100%",
  },
  packageDetailRouteImageFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  packageDetailRouteStep: {
    position: "absolute",
    left: 10,
    top: 10,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
  },
  packageDetailRouteStepText: {
    color: "#156436",
    fontSize: FONT_SIZES.xs,
    fontWeight: "900",
  },
  packageDetailRouteInfo: {
    padding: SPACING.sm,
    gap: 6,
  },
  packageDetailRouteName: {
    color: "#0F172A",
    fontSize: FONT_SIZES.sm,
    fontWeight: "800",
    lineHeight: 18,
  },
  packageDetailRouteMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  packageDetailRouteMeta: {
    flex: 1,
    color: "#64748B",
    fontSize: FONT_SIZES.xs,
    fontWeight: "600",
  },
  packageDetailRouteEmpty: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    gap: SPACING.sm,
  },
  packageDetailRouteEmptyText: {
    flex: 1,
    color: "#64748B",
    fontSize: FONT_SIZES.sm,
    fontWeight: "600",
    lineHeight: 19,
  },
  packageDetailFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    padding: SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
  },
  packageDetailFooterStack: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  packageDetailActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  packageDetailReserveButton: {
    borderRadius: 16,
    overflow: "hidden",
    minWidth: 132,
  },
  packageDetailReserveGradient: {
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  packageDetailReserveText: {
    color: COLORS.white,
    fontWeight: "800",
    fontSize: FONT_SIZES.md,
  },
  packageDetailCloseButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    backgroundColor: COLORS.white,
  },
  packageDetailCloseButtonFlex: {
    flex: 1,
  },
  packageDetailReserveButtonFlex: {
    flex: 1.2,
  },
  packageDetailCloseText: {
    color: "#334155",
    fontWeight: "700",
  },
};
