import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const packageStyles = {
  packageList: {
    paddingHorizontal: SPACING.md,
  },
  packageListContent: {
    gap: SPACING.md,
    paddingRight: SPACING.lg,
  },
  packageCard: {
    backgroundColor: COLORS.white,
    borderRadius: 28,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    shadowColor: "#0F172A",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  packageImageWrapper: {
    height: 220,
    position: "relative",
  },
  packageImage: {
    width: "100%",
    height: "100%",
  },
  packageImageFallback: {
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.xs,
    paddingHorizontal: SPACING.md,
  },
  packageFallbackText: {
    color: COLORS.white,
    fontWeight: "700",
    textAlign: "center",
  },
  packageImageOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
  },
  packageBadgeRow: {
    position: "absolute",
    top: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  packageDiscount: {
    backgroundColor: "#DC2626",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  packageDiscountText: {
    color: COLORS.white,
    fontWeight: "800",
    fontSize: FONT_SIZES.sm,
  },
  packageTag: {
    backgroundColor: "rgba(255,255,255,0.95)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
  },
  packageTagText: {
    color: "#0F172A",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  packageLocationRow: {
    position: "absolute",
    bottom: SPACING.md,
    left: SPACING.md,
    right: SPACING.md,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  packageLocationChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  packageLocationText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: FONT_SIZES.xs,
  },
  packageBody: {
    padding: SPACING.lg,
    gap: SPACING.sm,
  },
  packageVibeRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 2,
  },
  packageVibeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "rgba(251, 146, 60, 0.3)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  packageVibeText: {
    color: "#9A3412",
    fontWeight: "700",
    fontSize: FONT_SIZES.xs,
  },
  packageTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0F172A",
    lineHeight: 28,
  },
  packageRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  packageRatingText: {
    color: "#0F172A",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  packageAgency: {
    color: "#0E7490",
    fontWeight: "600",
    fontSize: FONT_SIZES.sm,
  },
  packageSubtitle: {
    color: "#475569",
    lineHeight: 22,
    fontSize: 15,
  },
  packageMetaCleanRow: {
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: 4,
  },
  packageMetaCleanItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  packageMetaCleanText: {
    color: "#475569",
    fontWeight: "600",
    fontSize: FONT_SIZES.sm,
  },
  packageIncludesClean: {
    marginTop: SPACING.xs,
    gap: 6,
  },
  packageIncludeCleanRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  packageIncludeBullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#10B981",
  },
  packageIncludeCleanText: {
    color: "#334155",
    fontSize: 14,
  },
  packageDivider: {
    height: 1,
    backgroundColor: "#F1F5F9",
    marginVertical: SPACING.md,
  },
  packageFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  packagePriceCol: {
    flex: 1,
  },
  packagePriceNote: {
    color: "#64748B",
    fontSize: FONT_SIZES.xs,
    textTransform: "uppercase",
    fontWeight: "700",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  packagePrice: {
    color: "#0F172A",
    fontWeight: "800",
    fontSize: 24,
  },
  packageButtonClean: {
    backgroundColor: "#0E7490",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
    gap: 8,
    shadowColor: "#0E7490",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  packageButtonCleanText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
  agencyChip: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    marginRight: SPACING.sm,
  },
  agencyChipText: {
    color: COLORS.text,
    fontWeight: "600",
    maxWidth: 180,
  },
  horizontalList: {
    paddingHorizontal: SPACING.lg,
    gap: SPACING.md,
    paddingRight: SPACING.xl,
  },
  
  // Filtering & Empty Agency States
  clearFilterBtn: {
    backgroundColor: "rgba(14, 116, 144, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  clearFilterText: {
    color: "#0E7490",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  emptyAgencyState: {
    marginHorizontal: SPACING.lg,
    backgroundColor: "rgba(255,255,255,0.6)",
    borderRadius: 32,
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.04)",
    marginTop: 10,
    marginBottom: 20,
  },
  emptyAgencyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyAgencyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 8,
    textAlign: "center",
  },
  emptyAgencySub: {
    fontSize: 14,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  restoreButton: {
    backgroundColor: "#FB923C",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  restoreButtonText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: FONT_SIZES.md,
  },
};
