import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const searchStyles = {
  searchCard: {
    padding: SPACING.lg,
    borderRadius: 28,
    gap: SPACING.md,
    backgroundColor: "#ffffff",
    shadowColor: "#0F172A",
    shadowOpacity: 0.1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F7F8FD",
    borderRadius: 12,
    paddingHorizontal: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.sm + 2,
    fontSize: FONT_SIZES.md,
    minHeight: 48,
  },
  searchIconButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingHorizontal: SPACING.md,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: "#5B3CF0",
  },
  searchIconLabel: {
    color: "#fff",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  searchActions: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  searchSuggestions: {
    borderTopWidth: 1,
    borderTopColor: "#E7EAF3",
    paddingTop: SPACING.xs,
    gap: SPACING.xs,
  },
  searchSuggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: 12,
    backgroundColor: "#F7F8FD",
  },
  searchSuggestionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    flex: 1,
  },
  searchSuggestionText: {
    color: COLORS.text,
    fontWeight: "600",
    flex: 1,
  },
  filterButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
  },
  filterButtonText: {
    color: "#475569",
    fontWeight: "700",
    fontSize: 14,
  },
  searchButton: {
    flex: 1.5,
    backgroundColor: "#5B3CF0",
    paddingVertical: 12,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#5B3CF0",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
  },
  searchButtonText: {
    color: COLORS.white,
    fontWeight: "700",
  },
};
