import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const searchStyles = {
  searchCard: {
    padding: SPACING.lg,
    borderRadius: 30,
    gap: SPACING.md,
    backgroundColor: "rgba(255,255,255,0.92)",
    shadowColor: "#0E7490",
    shadowOpacity: 0.12,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F6FEFC",
    borderRadius: 16,
    paddingHorizontal: SPACING.md,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.2)",
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.sm + 2,
    fontSize: FONT_SIZES.md,
    minHeight: 48,
  },
  searchIconButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingHorizontal: SPACING.md,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: "#0284C7",
  },
  searchIconLabel: {
    color: "#fff",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  searchActions: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  searchSuggestions: {
    borderTopWidth: 1,
    borderTopColor: "rgba(14, 116, 144, 0.12)",
    paddingTop: SPACING.xs,
    gap: SPACING.xs,
  },
  searchSuggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    borderRadius: 14,
    backgroundColor: "rgba(236, 254, 255, 0.9)",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.1)",
  },
  searchSuggestionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    flex: 1,
  },
  searchSuggestionText: {
    color: COLORS.text,
    fontWeight: "600",
    flex: 1,
  },
  filterButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.3)",
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: "#ECFEFF",
  },
  filterButtonText: {
    color: "#0F766E",
    fontWeight: "700",
    fontSize: 14,
  },
  searchButton: {
    flex: 1.5,
    backgroundColor: "#0284C7",
    paddingVertical: 12,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0284C7",
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  searchButtonText: {
    color: COLORS.white,
    fontWeight: "700",
  },
};
