import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export const sectionStyles = {
  section: {
    paddingVertical: SPACING.lg + 2,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
  },
  sectionText: {
    paddingHorizontal: SPACING.lg,
  },
  sectionTag: {
    alignSelf: "flex-start",
    color: "#14B8A6",
    fontWeight: "bold",
    marginBottom: SPACING.xs,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "bold",
    color: COLORS.text,
    marginBottom: SPACING.md,
  },
  sectionLink: {
    color: "#0E7490",
    fontWeight: "600",
  },
  sectionIntro: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md + 2,
  },
  sectionIconBubble: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(16, 185, 129, 0.16)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.18)",
  },
  sectionPill: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    backgroundColor: "#F8FAFC",
    color: "#64748B",
    fontWeight: "700",
    borderRadius: 999,
    fontSize: FONT_SIZES.xs,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sectionPillSecondary: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
    backgroundColor: "#E0F7FA",
    color: "#0E7490",
    fontWeight: "700",
    borderRadius: 999,
    fontSize: FONT_SIZES.xs,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sectionHeroTitle: {
    fontSize: 23,
    fontWeight: "800",
    color: "#063B35",
    textAlign: "left",
    letterSpacing: -0.2,
  },
  sectionTitleAccent: {
    width: 5,
    height: 24,
    backgroundColor: "#14B8A6",
    borderRadius: 2,
    marginRight: 12,
  },
  sectionDescription: {
    color: "#64748B",
    textAlign: "left",
    lineHeight: 20,
    fontSize: 14,
  },
  sectionAllIntro: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md,
    paddingTop: SPACING.lg,
  },
  categoriesSection: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.sm,
    backgroundColor: "#FFFFFF",
  },
  categoriesLabel: {
    color: COLORS.text,
    fontWeight: "700",
    marginBottom: SPACING.xs,
  },
  categoryTabs: {
    paddingVertical: SPACING.sm,
    gap: SPACING.sm,
    paddingHorizontal: SPACING.xs,
  },
  categoryTab: {
    paddingHorizontal: SPACING.md + 4,
    paddingVertical: SPACING.sm + 2,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    marginRight: 10,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  categoryTabActive: {
    backgroundColor: "#0E7490",
    borderColor: "#0E7490",
    shadowColor: "#0E7490",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  categoryTabText: {
    color: "#64748b",
    fontWeight: "600",
    fontSize: FONT_SIZES.sm,
    letterSpacing: 0.3,
  },
  categoryTabTextActive: {
    color: "#ffffff",
    fontWeight: "700",
  },
  categoryIndicator: {
    marginTop: 6,
    height: 3,
    width: 28,
    backgroundColor: "#0E7490",
    borderRadius: 12,
    alignSelf: "center",
  },
  // NearbyMapBlock
  mapCard: {
    marginHorizontal: SPACING.lg,
    borderRadius: 34,
    overflow: "hidden",
    height: 660,
    position: "relative",
    backgroundColor: "#FDFEFF",
    shadowColor: "#0E7490",
    shadowOpacity: 0.14,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.14)",
  },
  mapTouchWrapper: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  mapLockBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(236,254,255,0.95)",
    borderWidth: 1,
    borderColor: "rgba(14,116,144,0.3)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    zIndex: 20,
  },
  mapLockBadgePulseWrap: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 20,
  },
  mapLockBadgeText: {
    color: "#0E7490",
    fontSize: 11,
    fontWeight: "700",
  },
  mapLockBadgeHint: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(248,250,252,0.94)",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    zIndex: 20,
  },
  mapLockBadgeHintText: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "600",
  },
  mapNearbyCarrousel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 380,
    zIndex: 10,
    pointerEvents: "box-none",
  },
  mapCarrouselContent: {
    paddingHorizontal: SPACING.md,
    alignItems: "flex-end",
    gap: SPACING.sm + 2,
    paddingBottom: SPACING.xl,
  },
  mapEmptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAFC",
  },
  mapEmptyText: {
    color: "#64748B",
    fontSize: FONT_SIZES.sm,
    textAlign: "center",
    fontWeight: "500",
  },
  // New Empty State Card over map
  mapEmptyCard: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.xl,
    padding: SPACING.lg,
    borderRadius: 24,
    alignItems: "center",
    gap: SPACING.md,
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.12)",
    shadowColor: "#0E7490",
    shadowOpacity: 0.12,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  mapEmptyIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#E0F7FA",
    alignItems: "center",
    justifyContent: "center",
  },
  mapEmptyTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "800",
    color: "#1E293B",
  },
  mapEmptyDesc: {
    fontSize: FONT_SIZES.sm,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 18,
  },
  mapEmptyActions: {
    alignSelf: "stretch",
    gap: SPACING.sm,
  },
  mapEmptyButton: {
    backgroundColor: "#0284C7",
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.md,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: "#0284C7",
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  mapEmptyButtonSecondary: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(14, 116, 144, 0.24)",
    shadowOpacity: 0.08,
    elevation: 2,
  },
  mapEmptyButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
  mapEmptyButtonSecondaryText: {
    color: "#0E7490",
  },
  mapLoadingOverlay: {
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.xl,
    padding: SPACING.xl,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.5)",
  },
  mapLoadingText: {
    color: "#FB923C",
    fontWeight: "700",
    fontSize: FONT_SIZES.sm,
  },
};
