import { StyleSheet, Platform } from "react-native";
import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export default StyleSheet.create({
  sidePanelOverlayContainer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  sidePanelHandlePress: {
    position: "absolute",
    left: 0,
    top: "50%",
    width: 32,
    height: 120,
    marginTop: -60,
    alignItems: "center",
    justifyContent: "center",
  },
  sidePanelHandle: {
    position: "absolute",
    left: 8,
    top: "50%",
    width: 6,
    height: 84,
    marginTop: -42,
    borderRadius: 999,
    backgroundColor: "#0E7490",
  },
  sidePanelOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#0b1120",
  },
  sidePanel: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#F7FBFC",
    paddingTop: Platform.OS === "ios" ? SPACING.xxl * 1.2 : SPACING.lg,
    paddingHorizontal: SPACING.md,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    shadowColor: "#0F172A",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 6, height: 0 },
    elevation: 12,
  },
  sidePanelScrollContent: {
    paddingBottom: SPACING.xl,
  },
  sidePanelHeader: {
    marginBottom: SPACING.sm,
    marginTop: SPACING.xl,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  sidePanelTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "800",
    color: "#0F172A",
  },
  sidePanelSubtitle: {
    marginTop: 2,
    fontSize: FONT_SIZES.xs,
    color: "#64748B",
  },
  sidePanelLoader: {
    marginTop: SPACING.lg,
  },
  sidePanelEmpty: {
    marginTop: SPACING.lg,
    fontSize: FONT_SIZES.sm,
    color: "#64748B",
  },
  sidePanelList: {
    paddingBottom: SPACING.lg,
    gap: SPACING.md,
  },
  sidePanelItemCard: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 76,
    padding: SPACING.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DDE6EA",
    backgroundColor: "#FFFFFF",
    gap: SPACING.sm,
  },
  sidePanelThumb: {
    width: 56,
    height: 56,
    borderRadius: 10,
    backgroundColor: "#EEF2F6",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  sidePanelThumbImage: {
    width: "100%",
    height: "100%",
  },
  sidePanelItemInfo: {
    flex: 1,
  },
  sidePanelItemTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  sidePanelItemTitle: {
    flex: 1,
    fontSize: FONT_SIZES.md,
    fontWeight: "800",
    color: "#0F172A",
  },
  sidePanelRatingText: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
    color: "#047857",
  },
  sidePanelItemMeta: {
    flex: 1,
    fontSize: FONT_SIZES.xs,
    color: "#64748B",
    marginTop: 0,
  },
  sidePanelInlineMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 2,
  },
  sidePanelMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginTop: SPACING.sm,
  },
  sidePanelMetaPill: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "#D8F8E5",
  },
  sidePanelMetaPillText: {
    fontSize: 8,
    fontWeight: "800",
    color: "#047857",
  },
  sidePanelBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#063F2D",
  },
  sidePanelBadgeOutline: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 0,
    backgroundColor: "#CFFAE2",
  },
  sidePanelBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#047857",
  },
  sidePanelBadgeTextLight: {
    fontSize: 9,
    fontWeight: "800",
    color: COLORS.white,
  },
  sidePanelCountBadge: {
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#A7F3D0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.xs,
  },
  sidePanelCountText: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
    color: "#047857",
  },
  sidePanelNearbyCard: {
    padding: SPACING.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DDE6EA",
    backgroundColor: "#FFFFFF",
    marginBottom: SPACING.lg,
    overflow: "hidden",
  },
  sidePanelNearbyKicker: {
    marginBottom: SPACING.sm,
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
    color: "#047857",
  },
  sidePanelNearbyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  sidePanelNearbyThumb: {
    width: 82,
    height: 82,
    borderRadius: 11,
    backgroundColor: "#EEF2F6",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  sidePanelNearbyImage: {
    width: "100%",
    height: "100%",
  },
  sidePanelNearbyInfo: {
    flex: 1,
  },
  sidePanelCompactBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginBottom: 4,
  },
  sidePanelWelcomePill: {
    alignSelf: "flex-start",
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#CFFAE2",
    marginBottom: 4,
  },
  sidePanelNearbyTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  sidePanelNearbyTitle: {
    flex: 1,
    fontSize: FONT_SIZES.md,
    fontWeight: "800",
    color: "#0F172A",
  },
  sidePanelNearbyMetaRow: {
    marginTop: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  sidePanelNearbyMeta: {
    flex: 1,
    fontSize: FONT_SIZES.xs,
    color: "#64748B",
  },
  sidePanelNearbyDescription: {
    marginTop: SPACING.md,
    fontSize: FONT_SIZES.xs,
    lineHeight: 16,
    color: "#475569",
  },
  sidePanelDistancePill: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "#EAF7EF",
  },
  sidePanelNearbyActions: {
    marginTop: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  sidePanelVisitButton: {
    minHeight: 34,
    paddingHorizontal: SPACING.md,
    borderRadius: 999,
    backgroundColor: "#0E7490",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.xs,
  },
  sidePanelVisitButtonText: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "800",
    color: "#FFFFFF",
  },
});
