import { StyleSheet, Platform } from "react-native";
import { COLORS, FONT_SIZES, SPACING } from "../../../utils/constants";

export default StyleSheet.create({
  sidePanelOverlayContainer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  sidePanelHandlePress: {
    position: "absolute",
    left: 0,
    top: "50%",
    width: 32,
    height: 120,
    marginTop: -60,
    alignItems: "center",
    justifyContent: "center",
  },
  sidePanelHandle: {
    position: "absolute",
    left: 8,
    top: "50%",
    width: 6,
    height: 84,
    marginTop: -42,
    borderRadius: 999,
    backgroundColor: "#0E7490",
  },
  sidePanelOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#0b1120",
  },
  sidePanel: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#F8FAFF",
    paddingTop: Platform.OS === "ios" ? SPACING.xxl * 1.6 : SPACING.xl,
    paddingHorizontal: SPACING.lg,
    borderTopRightRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: "#0F172A",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 6, height: 0 },
    elevation: 12,
  },
  sidePanelScrollContent: {
    paddingBottom: SPACING.xl,
  },
  sidePanelHeader: {
    marginBottom: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  sidePanelTitle: {
    fontSize: FONT_SIZES.lg,
    fontWeight: "800",
    color: "#0E7490",
  },
  sidePanelSubtitle: {
    marginTop: 4,
    fontSize: FONT_SIZES.sm,
    color: "#64748B",
  },
  sidePanelLoader: {
    marginTop: SPACING.lg,
  },
  sidePanelEmpty: {
    marginTop: SPACING.lg,
    fontSize: FONT_SIZES.sm,
    color: "#64748B",
  },
  sidePanelList: {
    paddingBottom: SPACING.xl,
    gap: SPACING.sm,
  },
  sidePanelItemCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: SPACING.sm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    gap: SPACING.sm,
  },
  sidePanelThumb: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  sidePanelThumbImage: {
    width: "100%",
    height: "100%",
  },
  sidePanelItemInfo: {
    flex: 1,
  },
  sidePanelItemTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "700",
    color: "#0F172A",
  },
  sidePanelItemMeta: {
    fontSize: FONT_SIZES.sm,
    color: "#64748B",
    marginTop: 2,
  },
  sidePanelMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  sidePanelMetaPill: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#E0F7FA",
  },
  sidePanelMetaPillOutline: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#99F6E4",
  },
  sidePanelMetaPillText: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "600",
    color: "#0F766E",
  },
  sidePanelBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.xs,
    marginBottom: SPACING.sm,
  },
  sidePanelBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#0E7490",
  },
  sidePanelBadgeOutline: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#99F6E4",
    backgroundColor: "#E0F7FA",
  },
  sidePanelBadgeText: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "600",
    color: "#0F766E",
  },
  sidePanelBadgeTextLight: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "600",
    color: COLORS.white,
  },
  sidePanelCountBadge: {
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#E0F7FA",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.xs,
  },
  sidePanelCountText: {
    fontSize: FONT_SIZES.xs,
    fontWeight: "700",
    color: "#0E7490",
  },
  sidePanelWelcome: {
    padding: SPACING.md,
    backgroundColor: "#E0F7FA",
    borderRadius: 18,
    marginBottom: SPACING.lg,
  },
  sidePanelWelcomeTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "800",
    color: "#0F172A",
  },
  sidePanelWelcomeSubtitle: {
    marginTop: 4,
    fontSize: FONT_SIZES.sm,
    color: "#475569",
  },
  sidePanelNearbyCard: {
    padding: SPACING.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
    marginBottom: SPACING.lg,
  },
  sidePanelNearbyImage: {
    width: "100%",
    height: 120,
    borderRadius: 12,
    marginBottom: SPACING.sm,
  },
  sidePanelNearbyTitle: {
    fontSize: FONT_SIZES.md,
    fontWeight: "700",
    color: "#0F172A",
  },
  sidePanelNearbyMeta: {
    marginTop: 4,
    fontSize: FONT_SIZES.sm,
    color: "#64748B",
  },
  sidePanelNearbyDescription: {
    marginTop: 6,
    fontSize: FONT_SIZES.sm,
    color: "#475569",
  },
});
